// Code generated by sqlc. DO NOT EDIT BY HAND in a real project.
// See models.go for why this is hand-written in the demo repo.
package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgxpool"
)

// Queries wraps a pgxpool.Pool directly. sqlc can instead generate this to
// accept a DBTX interface (satisfied by both *pgxpool.Pool and pgx.Tx) so
// the same generated queries work inside a transaction; trimmed to the
// concrete pool type here to keep the demo compact.
type Queries struct {
	pool *pgxpool.Pool
}

func New(pool *pgxpool.Pool) *Queries {
	return &Queries{pool: pool}
}
