// Code generated by sqlc. DO NOT EDIT BY HAND in a real project.
//
// NOTE for reviewers: in this demo repo these files are hand-written to
// mirror sqlc's exact output shape, so the project builds without requiring
// the sqlc CLI to be installed. In the real migration, `make generate`
// (see Makefile) runs `sqlc generate` from db/queries/*.sql against
// db/migrations/*.sql and this package is fully generated + committed,
// which is standard sqlc practice.
package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Policyholder struct {
	ID        pgtype.UUID
	FullName  string
	Email     string
	Phone     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Policy struct {
	ID             pgtype.UUID
	PolicyholderID pgtype.UUID
	Carrier        string
	PolicyNumber   string
	LineOfBusiness string
	EffectiveDate  pgtype.Date
	ExpirationDate pgtype.Date
	PremiumCents   int64
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Note struct {
	ID             pgtype.UUID
	PolicyholderID pgtype.UUID
	Author         string
	Body           string
	CreatedAt      pgtype.Timestamptz
}
