// Code generated by sqlc. DO NOT EDIT BY HAND in a real project.
// See models.go for why this is hand-written in the demo repo.
// Source query file: db/queries/policyholders.sql
package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyholder = `-- name: CreatePolicyholder :one
INSERT INTO policyholders (full_name, email, phone)
VALUES ($1, $2, $3)
RETURNING id, full_name, email, phone, created_at, updated_at
`

type CreatePolicyholderParams struct {
	FullName string
	Email    string
	Phone    pgtype.Text
}

func (q *Queries) CreatePolicyholder(ctx context.Context, arg CreatePolicyholderParams) (Policyholder, error) {
	row := q.pool.QueryRow(ctx, createPolicyholder, arg.FullName, arg.Email, arg.Phone)
	var i Policyholder
	err := row.Scan(&i.ID, &i.FullName, &i.Email, &i.Phone, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getPolicyholder = `-- name: GetPolicyholder :one
SELECT id, full_name, email, phone, created_at, updated_at FROM policyholders WHERE id = $1
`

func (q *Queries) GetPolicyholder(ctx context.Context, id pgtype.UUID) (Policyholder, error) {
	row := q.pool.QueryRow(ctx, getPolicyholder, id)
	var i Policyholder
	err := row.Scan(&i.ID, &i.FullName, &i.Email, &i.Phone, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listPolicyholders = `-- name: ListPolicyholders :many
SELECT id, full_name, email, phone, created_at, updated_at FROM policyholders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPolicyholdersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPolicyholders(ctx context.Context, arg ListPolicyholdersParams) ([]Policyholder, error) {
	rows, err := q.pool.Query(ctx, listPolicyholders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policyholder
	for rows.Next() {
		var i Policyholder
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email, &i.Phone, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const searchPolicyholders = `-- name: SearchPolicyholders :many
SELECT id, full_name, email, phone, created_at, updated_at FROM policyholders
WHERE full_name ILIKE '%' || $3::text || '%'
   OR email ILIKE '%' || $3::text || '%'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchPolicyholdersParams struct {
	Limit  int32
	Offset int32
	Query  string
}

func (q *Queries) SearchPolicyholders(ctx context.Context, arg SearchPolicyholdersParams) ([]Policyholder, error) {
	rows, err := q.pool.Query(ctx, searchPolicyholders, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policyholder
	for rows.Next() {
		var i Policyholder
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email, &i.Phone, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updatePolicyholder = `-- name: UpdatePolicyholder :one
UPDATE policyholders
SET full_name = $2, email = $3, phone = $4, updated_at = now()
WHERE id = $1
RETURNING id, full_name, email, phone, created_at, updated_at
`

type UpdatePolicyholderParams struct {
	ID       pgtype.UUID
	FullName string
	Email    string
	Phone    pgtype.Text
}

func (q *Queries) UpdatePolicyholder(ctx context.Context, arg UpdatePolicyholderParams) (Policyholder, error) {
	row := q.pool.QueryRow(ctx, updatePolicyholder, arg.ID, arg.FullName, arg.Email, arg.Phone)
	var i Policyholder
	err := row.Scan(&i.ID, &i.FullName, &i.Email, &i.Phone, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deletePolicyholder = `-- name: DeletePolicyholder :exec
DELETE FROM policyholders WHERE id = $1
`

func (q *Queries) DeletePolicyholder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.pool.Exec(ctx, deletePolicyholder, id)
	return err
}
