// Code generated by sqlc. DO NOT EDIT BY HAND in a real project.
// See models.go for why this is hand-written in the demo repo.
// Source query file: db/queries/policies.sql
package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (
    policyholder_id, carrier, policy_number, line_of_business,
    effective_date, expiration_date, premium_cents, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, policyholder_id, carrier, policy_number, line_of_business,
          effective_date, expiration_date, premium_cents, status, created_at, updated_at
`

type CreatePolicyParams struct {
	PolicyholderID pgtype.UUID
	Carrier        string
	PolicyNumber   string
	LineOfBusiness string
	EffectiveDate  pgtype.Date
	ExpirationDate pgtype.Date
	PremiumCents   int64
	Status         string
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.pool.QueryRow(ctx, createPolicy,
		arg.PolicyholderID, arg.Carrier, arg.PolicyNumber, arg.LineOfBusiness,
		arg.EffectiveDate, arg.ExpirationDate, arg.PremiumCents, arg.Status)
	var i Policy
	err := row.Scan(&i.ID, &i.PolicyholderID, &i.Carrier, &i.PolicyNumber, &i.LineOfBusiness,
		&i.EffectiveDate, &i.ExpirationDate, &i.PremiumCents, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, policyholder_id, carrier, policy_number, line_of_business,
       effective_date, expiration_date, premium_cents, status, created_at, updated_at
FROM policies WHERE id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, id pgtype.UUID) (Policy, error) {
	row := q.pool.QueryRow(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(&i.ID, &i.PolicyholderID, &i.Carrier, &i.PolicyNumber, &i.LineOfBusiness,
		&i.EffectiveDate, &i.ExpirationDate, &i.PremiumCents, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listPoliciesByPolicyholder = `-- name: ListPoliciesByPolicyholder :many
SELECT id, policyholder_id, carrier, policy_number, line_of_business,
       effective_date, expiration_date, premium_cents, status, created_at, updated_at
FROM policies
WHERE policyholder_id = $1
ORDER BY effective_date DESC
`

func (q *Queries) ListPoliciesByPolicyholder(ctx context.Context, policyholderID pgtype.UUID) ([]Policy, error) {
	rows, err := q.pool.Query(ctx, listPoliciesByPolicyholder, policyholderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(&i.ID, &i.PolicyholderID, &i.Carrier, &i.PolicyNumber, &i.LineOfBusiness,
			&i.EffectiveDate, &i.ExpirationDate, &i.PremiumCents, &i.Status, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listExpiringPolicies = `-- name: ListExpiringPolicies :many
SELECT id, policyholder_id, carrier, policy_number, line_of_business,
       effective_date, expiration_date, premium_cents, status, created_at, updated_at
FROM policies
WHERE expiration_date BETWEEN now()::date AND (now()::date + $1::int)
  AND status = 'active'
ORDER BY expiration_date ASC
`

func (q *Queries) ListExpiringPolicies(ctx context.Context, withinDays int32) ([]Policy, error) {
	rows, err := q.pool.Query(ctx, listExpiringPolicies, withinDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(&i.ID, &i.PolicyholderID, &i.Carrier, &i.PolicyNumber, &i.LineOfBusiness,
			&i.EffectiveDate, &i.ExpirationDate, &i.PremiumCents, &i.Status, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updatePolicyStatus = `-- name: UpdatePolicyStatus :one
UPDATE policies
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, policyholder_id, carrier, policy_number, line_of_business,
          effective_date, expiration_date, premium_cents, status, created_at, updated_at
`

type UpdatePolicyStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdatePolicyStatus(ctx context.Context, arg UpdatePolicyStatusParams) (Policy, error) {
	row := q.pool.QueryRow(ctx, updatePolicyStatus, arg.ID, arg.Status)
	var i Policy
	err := row.Scan(&i.ID, &i.PolicyholderID, &i.Carrier, &i.PolicyNumber, &i.LineOfBusiness,
		&i.EffectiveDate, &i.ExpirationDate, &i.PremiumCents, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.pool.Exec(ctx, deletePolicy, id)
	return err
}
